# Generated by Django 5.0 on 2024-06-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TasksApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='TasksApp'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
