# Generated by Django 5.0 on 2024-06-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TasksApp', '0003_taskmodel_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='img',
            field=models.ImageField(null=True, upload_to='TasksApp'),
        ),
    ]
