# Generated by Django 5.0 on 2024-06-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TasksApp', '0004_alter_taskmodel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='TasksApp'),
        ),
    ]
